#!/usr/bin/env python3
"""2026 Emmys — what's OK to watch with kids. Regenerated by build_web.py."""

from __future__ import annotations

import html

UPDATED = "2026-09-18"
UPDATED_DISPLAY = "September 18, 2026"
SLUG = "emmys-2026"


def _esc(value) -> str:
    return html.escape(str(value or ""), quote=True)


def _pct(mixes: dict, sid: str) -> str:
    mix = mixes.get(sid) or {}
    total = mix.get("total") or 0
    if not total:
        return ""
    safe = round(100 * mix["safe"] / total)
    maybe = round(100 * mix["maybe"] / total)
    skip = max(0, 100 - safe - maybe)
    if safe + maybe > 100:
        maybe = max(0, 100 - safe)
        skip = 0
    return f"{safe}% mild, {maybe}% caution, {skip}% too much"


def _verdict_class(verdict: str) -> str:
    if verdict == "play":
        return "play"
    if verdict == "skip":
        return "skip"
    return "preview"


def _pick_html(pick: dict) -> str:
    chips = "".join(f"<li>{_esc(item)}</li>" for item in pick.get("watch_for") or [])
    watch = (
        f'<p class="wo-watch-label">Watch for</p><ul class="wo-watch">{chips}</ul>'
        if chips
        else ""
    )
    catalog = ""
    if pick.get("catalog"):
        catalog = (
            f'<p class="wo-catalog">Episode scores: '
            f'<a href="{_esc(pick["catalog"])}">{_esc(pick.get("catalog_label") or "open the show page")}</a>.</p>'
        )
    cover = ""
    if pick.get("cover"):
        cover = (
            f'<img class="emmy-cover" src="covers/{_esc(pick["cover"])}" alt="" '
            f'width="160" height="220" loading="lazy" />'
        )
    award = f'<p class="emmy-award">{pick["award"]}</p>' if pick.get("award") else ""
    return f"""    <article class="wo-pick emmy-pick {_verdict_class(pick["verdict"])}">
      {cover}
      <div class="emmy-pick-body">
      <header class="wo-pick-head">
        <p class="wo-verdict">{_esc(pick["verdict_label"])}</p>
        <h3>{_esc(pick["title"])}</h3>
        <p class="wo-meta">{_esc(pick["meta"])}</p>
      </header>
      {award}
      <p>{pick["why"]}</p>
      {watch}
      {catalog}
      </div>
    </article>"""


def _picks(items: list[dict]) -> str:
    return "\n".join(_pick_html(p) for p in items)


def page_data(mixes: dict) -> dict:
    simpsons = _pct(mixes, "simpsons") or "about half the episodes mild"
    burgers = _pct(mixes, "bobs-burgers") or "mixed — check the episode"
    south = _pct(mixes, "south-park") or "mostly too much"
    rick = _pct(mixes, "rick-and-morty") or "almost all too much"

    play = [
        {
            "title": "The Muppet Show",
            "cover": "muppet-show.jpg",
            "verdict": "play",
            "verdict_label": "Play tonight",
            "meta": "Disney+ · family variety special · all ages with a parent",
            "award": "Four Creative Arts Emmys, including Outstanding Variety Special (Pre-Recorded).",
            "why": (
                "The family pick from Primetime night. Disney+ brought Kermit back as a "
                "pre-recorded special (Sabrina Carpenter guest). Classic Muppet energy: "
                "songs, chaos, the kind of mild innuendo adults catch and kids miss. Not a "
                "full series — one special — and the only trophy cluster you can actually "
                "put on before bedtime."
            ),
            "watch_for": [
                "Grown-up asides in the variety-show tradition",
                "Loud puppet slapstick",
            ],
        },
        {
            "title": "Abbott Elementary",
            "cover": "abbott-elementary.jpg",
            "verdict": "play",
            "verdict_label": "Family couch · 10+",
            "meta": "ABC / Hulu · TV-PG school sitcom · older kids",
            "award": "Outstanding Comedy Series nominee — lost to Widow's Bay.",
            "why": (
                "The most kid-reasonable comedy in a category full of TV-MA shows. It's a "
                "Philadelphia public-school workplace sitcom: mockumentary talking heads, "
                "underfunded classrooms, Quinta Brunson. TV-PG language and adult workplace "
                "jokes exist; sex plots and gore do not. Fine for most 10+ with you in the "
                "room. Episode-by-episode scores are on the show page — 60 mild, 23 caution, "
                "10 too much."
            ),
            "watch_for": [
                "Occasional swearing and innuendo",
                "Grown-up dating / workplace stress",
                "Kids on screen who are characters, not the audience",
            ],
        },
        {
            "title": "Antiques Roadshow",
            "cover": "antiques-roadshow.jpg",
            "verdict": "play",
            "verdict_label": "Play tonight",
            "meta": "PBS · structured reality winner · all ages",
            "award": "Outstanding Structured Reality Program.",
            "why": (
                "People bring grandma's lamp; an expert says it's worth $12 or $12,000. "
                "No plot, no jump scares, no language. If the Emmys are on in the other "
                "room and you need a true all-clear, this is it."
            ),
            "watch_for": ["The occasional sad family story attached to an object"],
        },
        {
            "title": "Jeopardy!",
            "cover": "jeopardy.jpg",
            "verdict": "play",
            "verdict_label": "Play tonight",
            "meta": "ABC / syndication · game show · 8+",
            "award": "Outstanding Game Show.",
            "why": (
                "Trivia with Ken Jennings. Clues can name adult news, history, or a spicy "
                "category title; nothing is graphic. Better than putting the actual Emmys "
                "telecast on — that show is built out of clips from Widow's Bay and The Pitt."
            ),
            "watch_for": ["Clues about adult movies, news, or history"],
        },
        {
            "title": "Ocean with David Attenborough",
            "cover": "ocean-attenborough.jpg",
            "verdict": "play",
            "verdict_label": "Play · some nature intensity",
            "meta": "National Geographic / Disney+ · documentary special · 8+",
            "award": "Nominated for Outstanding Documentary or Nonfiction Special; multiple craft nods.",
            "why": (
                "Real ocean footage, Attenborough's voice, climate stakes. Beautiful, and "
                "not a cartoon. Predators eat prey; reefs bleach. Fine for most elementary "
                "kids who already do Planet Earth; sit with younger ones for the grim bits."
            ),
            "watch_for": [
                "Animal death and hunting",
                "Climate / habitat-loss sequences",
            ],
        },
    ]

    kids_emmys = [
        {
            "title": "Sesame Street",
            "cover": "sesame-street.jpg",
            "verdict": "play",
            "verdict_label": "Preschool pick",
            "meta": "Netflix (moved from HBO Max) · preschool · 2–6",
            "award": "Children's & Family Emmy: Outstanding Preschool, Children's or Family Viewing Series (March 2026).",
            "why": (
                "The actual kids awards happened in March. Sesame Street took the top "
                "family-viewing series prize, plus short-form for the Andrew Garfield / Elmo "
                "grief video. If someone in the house is under seven, start here — not with "
                "whatever won on Primetime night."
            ),
            "watch_for": ["Feelings episodes that can get quietly sad"],
        },
        {
            "title": "The Tiny Chef Show",
            "cover": "tiny-chef.jpg",
            "verdict": "play",
            "verdict_label": "Preschool pick",
            "meta": "Nickelodeon · preschool animation · 3–7",
            "award": "Outstanding Preschool Animated Series.",
            "why": (
                "A two-inch chef cooks real-ish food with celebrity drop-ins. Gentle, "
                "crafty, and short. The Spooky Stump special also won directing — that's "
                "Halloween-light, not horror."
            ),
            "watch_for": ["Mild pretend-spooky episodes around Halloween"],
        },
        {
            "title": "Win or Lose",
            "cover": "win-or-lose.jpg",
            "verdict": "play",
            "verdict_label": "Play · elementary+",
            "meta": "Disney+ · Pixar · 7–12",
            "award": "Outstanding Children's or Young Teen Animated Series (four trophies).",
            "why": (
                "Pixar's softball-team anthology: each episode is a different kid's point "
                "of view of the same week. Big feelings, crushes, parents who don't get it. "
                "Not preschool, not edgy. The Children's Emmy animation winner, and a better "
                "family-night pick than any Primetime comedy nominee except Abbott."
            ),
            "watch_for": [
                "Social anxiety and family tension",
                "A crush / identity beat — talk, don't panic",
            ],
        },
        {
            "title": "Descendants: The Rise of Red",
            "cover": "descendants-rise-of-red.jpg",
            "verdict": "play",
            "verdict_label": "Play · Disney Channel energy",
            "meta": "Disney+ · musical special · 6–12",
            "award": "Outstanding Fiction Special — night's most-awarded Children's Emmy show (five trophies).",
            "why": (
                "Disney villain-kids musical. Songs, hats, a Queen of Hearts plot. Typical "
                "Descendants: theatrical 'danger,' mild romance, nothing you need to "
                "preview unless musicals themselves are a hard pass in your house."
            ),
            "watch_for": ["Villain theatrics and a tween crush"],
        },
        {
            "title": "A Real Bug's Life",
            "cover": "a-real-bugs-life.jpg",
            "verdict": "play",
            "verdict_label": "Play tonight",
            "meta": "National Geographic / Disney+ · nature · 5+",
            "award": "Outstanding Informational Program.",
            "why": (
                "Macro bugs, Tiny-world nature series. Some predator-prey shots; no people "
                "swearing. An easy 'they won an Emmy' night for elementary kids."
            ),
            "watch_for": ["Insects eating insects"],
        },
    ]

    preview = [
        {
            "title": "Love on the Spectrum",
            "cover": "love-on-the-spectrum.jpg",
            "verdict": "preview",
            "verdict_label": "Tweens / teens with you",
            "meta": "Netflix · unstructured reality winner · 12+",
            "award": "Outstanding Unstructured Reality Program.",
            "why": (
                "Autistic adults dating, with a lot of kindness and some kissing. Not "
                "preschool, not raunchy. A strong watch-together for older kids if you want "
                "the conversation about neurodiversity and dating. Skip if your couch is "
                "full of six-year-olds."
            ),
            "watch_for": [
                "Dating, kissing, breakups",
                "Emotional conversations that can overwhelm younger kids",
            ],
        },
        {
            "title": "Star Wars: Skeleton Crew",
            "cover": "skeleton-crew.jpg",
            "verdict": "preview",
            "verdict_label": "Tweens · some peril",
            "meta": "Disney+ · live-action Star Wars · 8–12",
            "award": "Children's & Family Emmy: Outstanding Young Teen Series (four trophies).",
            "why": (
                "Kids get lost in the Star Wars galaxy. It's aimed at them — and it still "
                "has blasters, creatures, and 'are we going to die' sequences. Fine for "
                "Clone Wars households; too much for Bluey-only nights."
            ),
            "watch_for": ["Space battles, kidnaps, creature scares"],
            "catalog": "/clone-wars",
            "catalog_label": "We scored The Clone Wars if you want the safer Star Wars lane",
        },
        {
            "title": "Heartstopper",
            "cover": "heartstopper.jpg",
            "verdict": "preview",
            "verdict_label": "Teens — not little kids",
            "meta": "Netflix · teen romance · 13+",
            "award": "Joe Locke won Outstanding Lead Performer in a Children's & Family program.",
            "why": (
                "A Children's Emmy performer win does not make this a kids' show. It's a "
                "tender British teen LGBTQ romance: kissing, homophobic bullying, mental "
                "health. Excellent for teens with a parent nearby. Wrong room for anyone "
                "still in elementary school."
            ),
            "watch_for": [
                "Teen kissing and coming-out storylines",
                "Bullying / homophobia depicted so it can be rejected",
                "Anxiety and self-harm conversation in later seasons",
            ],
        },
        {
            "title": "Sweet Tooth",
            "cover": "sweet-tooth.jpg",
            "verdict": "preview",
            "verdict_label": "Tweens+ · post-apocalyptic",
            "meta": "Netflix · fantasy adventure · 12+",
            "award": "Five Children's & Family Emmys, including supporting and younger performer.",
            "why": (
                "Hybrid deer-boy in a collapsed world. Adventure, found family, and enough "
                "violence / grim world-building that it is not a substitute for Paddington. "
                "Older elementary kids who already do Stranger-Things-lite fantasy can try "
                "it; we would not start here."
            ),
            "watch_for": ["Post-collapse violence, guns, dead parents, creature peril"],
        },
        {
            "title": "Only Murders in the Building",
            "cover": "only-murders.jpg",
            "verdict": "preview",
            "verdict_label": "Older kids / teens",
            "meta": "Hulu · comedy mystery · 13+",
            "award": "Outstanding Comedy Series nominee; Martin Short nominated for lead actor.",
            "why": (
                "Steve Martin, Martin Short, Selena Gomez solve murders in a New York "
                "building. Funny, sweary, and the plot is literally homicide. Better as a "
                "teen-and-up watch than a family sitcom."
            ),
            "watch_for": ["Murder mystery, corpses, adult language, innuendo"],
        },
        {
            "title": "The Simpsons",
            "cover": "simpsons.jpg",
            "verdict": "preview",
            "verdict_label": "Depends on the episode",
            "meta": f"Fox / Disney+ · animated program nominee · {simpsons}",
            "award": 'Nominated for Outstanding Animated Program ("Homer? A Cracker Bro?").',
            "why": (
                f"A nominee, not the winner. We scored 564 episodes: {simpsons}. "
                "Early seasons are the family-couch ones; later ones wander. Don't treat "
                "the Emmy nomination as a green light for a random episode."
            ),
            "watch_for": ["Swearing, adult gags, the occasional scary or crude plot"],
            "catalog": "/guides/simpsons",
            "catalog_label": "Safest Simpsons episodes first",
        },
        {
            "title": "Bob's Burgers",
            "cover": "bobs-burgers.jpg",
            "verdict": "preview",
            "verdict_label": "Depends on the episode",
            "meta": f"Fox / Hulu · animated program nominee · {burgers}",
            "award": 'Nominated for Outstanding Animated Program ("Grand Pre-Pre-Pre-Opening").',
            "why": (
                f"Warm family, lots of innuendo. We scored 309 episodes: {burgers}. "
                "Some nights are a Belcher hug; some nights are a sex joke you didn't "
                "budget for. Use the skip list."
            ),
            "watch_for": ["Innuendo, mild swearing, adult B-plots"],
            "catalog": "/guides/bobs-burgers",
            "catalog_label": "Safest Bob's Burgers episodes first",
        },
        {
            "title": "Star Wars: Visions",
            "cover": "star-wars-visions.jpg",
            "verdict": "preview",
            "verdict_label": "Check the short",
            "meta": "Disney+ · adult-leaning anthology · 12+",
            "award": 'Nominated for Outstanding Animated Program ("BLACK"); craft wins on "The Duel: Payback".',
            "why": (
                "An anthology of shorts from different studios. Some are lyrical; the "
                "nominated ones are stylish and violent. Do not assume 'Star Wars cartoon' "
                "means Clone Wars. Preview the specific episode."
            ),
            "watch_for": ["Lightsaber gore, darker adult shorts mixed with kid-friendlier ones"],
        },
    ]

    skip = [
        {
            "title": "Widow's Bay",
            "cover": "widows-bay.jpg",
            "verdict": "skip",
            "verdict_label": "Skip with the kids",
            "meta": "Apple TV+ · TV-MA horror comedy · adults",
            "award": "Outstanding Comedy Series — the biggest comedy trophy of the night.",
            "why": (
                "This is the trap. It won comedy. It is not a sitcom. Matthew Rhys is the "
                "mayor of a cursed New England island; the locals were right about the "
                "ghosts. Jump scares, a 1990s serial-killer backstory involving teen girls, "
                "strong language, drinking. Common Sense lands around 14+; Apple rates it "
                "TV-MA. If the kids heard 'best comedy' on the recap, this is the one to "
                "shut down."
            ),
            "watch_for": [
                "Horror scares and a haunted-island curse",
                "Serial-killer history, death, strong language",
            ],
        },
        {
            "title": "The Pitt",
            "cover": "the-pitt.jpg",
            "verdict": "skip",
            "verdict_label": "Skip with the kids",
            "meta": "HBO Max · medical drama winner · adults",
            "award": "Outstanding Drama Series. Noah Wyle won lead actor.",
            "why": (
                "A real-time ER shift. Blood, codes, dying patients, the kind of medicine "
                "TV that is designed to stress adults. Not 'they learn about doctors.'"
            ),
            "watch_for": ["Medical gore, death, trauma"],
        },
        {
            "title": "South Park",
            "cover": "south-park.jpg",
            "verdict": "skip",
            "verdict_label": "Skip with the kids",
            "meta": f"Comedy Central · animated program winner · {south}",
            "award": 'Outstanding Animated Program — "Sermon on the \'Mount".',
            "why": (
                f"The cartoon that won is the one you already knew not to put on. "
                f"We scored 334 episodes: {south}. A handful of milder ones exist; they "
                "are not why it won an Emmy."
            ),
            "watch_for": ["Everything: language, sex, violence, topical cruelty"],
            "catalog": "/guides/south-park",
            "catalog_label": "The few milder episodes, if you insist",
        },
        {
            "title": "Rick and Morty",
            "cover": "rick-and-morty.jpg",
            "verdict": "skip",
            "verdict_label": "Skip with the kids",
            "meta": f"Adult Swim · animated nominee · {rick}",
            "award": 'Nominated for Outstanding Animated Program ("There\'s Something About Morty").',
            "why": (
                f"Nominated next to The Simpsons; not in the same universe for a family "
                f"couch. We scored 82 episodes: {rick}."
            ),
            "watch_for": ["Body horror, sex, nihilism, constant swearing"],
            "catalog": "/guides/rick-and-morty",
            "catalog_label": "See how rough the catalog actually is",
        },
        {
            "title": "The rest of comedy / drama night",
            "cover": "hacks.jpg",
            "verdict": "skip",
            "verdict_label": "Not kids' TV",
            "meta": "Hacks · The Bear · Beef · DTF St. Louis · Euphoria · The Traitors",
            "award": "Jean Smart (Hacks), DTF St. Louis (limited series), The Traitors (reality competition).",
            "why": (
                "Hacks is a blistering showbiz comedy. The Bear is kitchen panic and "
                "language. Beef is rage. DTF St. Louis won limited series — the title is "
                "the warning. Zendaya was nominated for Euphoria. The Traitors is a "
                "backstabbing reality game. None of these belong on a kids' list just "
                "because they were on the telecast."
            ),
            "watch_for": ["TV-MA language, sex, violence, or adult reality scheming"],
        },
    ]

    faqs = [
        (
            "What from the 2026 Emmys can I watch with kids?",
            "From Primetime: <strong>The Muppet Show</strong> on Disney+, "
            "<strong>Abbott Elementary</strong> with older kids, "
            "<strong>Antiques Roadshow</strong>, <strong>Jeopardy!</strong>, and "
            "<strong>Ocean with David Attenborough</strong>. The real kids trophies "
            "are the March Children's &amp; Family Emmys: Sesame Street, The Tiny Chef Show, "
            "Win or Lose, Descendants: The Rise of Red.",
        ),
        (
            "Is Widow's Bay OK for kids? It won Outstanding Comedy Series.",
            "No. Widow's Bay is a TV-MA horror-comedy about a cursed island, not a family "
            "sitcom. Jump scares, a serial-killer backstory, strong language. The Emmy is "
            "for adults.",
        ),
        (
            "Is Abbott Elementary OK for kids?",
            "Usually for about 10+ with a parent nearby. It's TV-PG: school-workplace jokes, "
            "some language, no gore. It was nominated for Outstanding Comedy Series and lost "
            "to Widow's Bay. We have not scored every episode yet.",
        ),
        (
            "Can kids watch the Emmys ceremony itself?",
            "We wouldn't. The telecast is built around clips and jokes from TV-MA shows. "
            "Put on the Muppet special or a Children's Emmy winner instead of the awards show.",
        ),
        (
            "Did South Park really win an Emmy?",
            'Yes — Outstanding Animated Program for "Sermon on the \'Mount". That is not a '
            "kids' cartoon win. The other nominees included The Simpsons and Bob's Burgers, "
            "which we have scored episode by episode.",
        ),
        (
            "What's the difference between the Primetime Emmys and the Children's & Family Emmys?",
            "Primetime (September 14, 2026) is the famous night — drama, comedy, limited "
            "series. Children's &amp; Family Emmys (March 2026) are a separate NATAS show "
            "for preschool, kids, and young-teen programs. If you want 'Emmy winner' and "
            "little kids, use the March list.",
        ),
    ]

    return {
        "play": play,
        "kids_emmys": kids_emmys,
        "preview": preview,
        "skip": skip,
        "faqs": faqs,
    }


def page_body(mixes: dict) -> str:
    data = page_data(mixes)
    from build_web import faq_html

    return f"""  <nav class="topnav wrap">
    <a class="back-home" href="/">← All shows</a>
    <a class="back-home subtle" href="/whats-on/">What's on</a>
    <a class="back-home subtle" href="/guides/">What to watch</a>
  </nav>
  <nav class="emmy-jump-bar" aria-label="On this page">
    <div class="wrap emmy-jump">
      <p class="emmy-jump-kicker">Jump to</p>
      <a class="emmy-jump-play" href="#play">Play tonight</a>
      <a class="emmy-jump-kids" href="#kids-emmys">Kids' Emmys</a>
      <a class="emmy-jump-older" href="#preview">Older kids</a>
      <a class="emmy-jump-skip" href="#skip">Skip with kids</a>
      <a class="emmy-jump-faq" href="#faq">Questions</a>
    </div>
  </nav>
  <header class="hero wo-hero">
    <div class="wrap hero-inner">
      <div class="hero-copy">
        <p class="eyebrow">78th Primetime Emmys · September 14, 2026</p>
        <h1>What's OK to watch with kids from the 2026 Emmys</h1>
        <p class="tagline">
          Awards are not a kids' rating. Most winners this year are adult TV.
          Here's the short list — plus the Children's &amp; Family Emmys, which
          are the trophies that were actually aimed at your couch.
        </p>
        <p class="wo-updated">Updated {UPDATED_DISPLAY}. Informal parent notes — not episode-by-episode scores unless we say so.</p>
      </div>
      <aside class="hero-card" aria-hidden="true">
        <div class="guide-hero-covers">
          <img src="covers/muppet-show.jpg" alt="" width="480" height="270" />
          <img src="covers/abbott-elementary.jpg" alt="" width="480" height="270" />
          <img src="covers/sesame-street.jpg" alt="" width="480" height="270" />
          <img src="covers/win-or-lose.jpg" alt="" width="480" height="270" />
        </div>
      </aside>
    </div>
  </header>
  <main class="wrap wo-page emmy-page">
    <aside class="wo-tonight">
      <p class="wo-tonight-kicker">The headline</p>
      <p>
        <strong>Widow's Bay</strong> won Outstanding Comedy Series. It is a TV-MA
        haunted-island horror comedy — not a family sitcom. Put on
        <strong>The Muppet Show</strong> (Disney+), <strong>Abbott Elementary</strong>
        with older kids, or <strong>Sesame Street</strong> / <strong>Win or Lose</strong>
        from the Children's Emmys.
      </p>
    </aside>
    <section class="wo-section" id="play">
      <h2>Play with the kids — Primetime</h2>
      <p class="emmy-sec-lead">The September 14 telecast. A short list on purpose.</p>
      <div class="wo-picks">
{_picks(data["play"])}
      </div>
    </section>
    <section class="wo-section" id="kids-emmys">
      <h2>Children's &amp; Family Emmys — the actual kids trophies</h2>
      <p class="emmy-sec-lead">
        Separate ceremony, March 2, 2026, run by NATAS. If you want “Emmy winner”
        and little kids, this is the list — not Widow's Bay.
      </p>
      <div class="wo-picks">
{_picks(data["kids_emmys"])}
      </div>
    </section>
    <section class="wo-section" id="preview">
      <h2>Older kids — preview first</h2>
      <p class="emmy-sec-lead">Tweens and teens, not a preschool couch.</p>
      <div class="wo-picks">
{_picks(data["preview"])}
      </div>
    </section>
    <section class="wo-section" id="skip">
      <h2>Won an Emmy. Still a no.</h2>
      <p class="emmy-sec-lead">The trophies everyone is talking about.</p>
      <div class="wo-picks">
{_picks(data["skip"])}
      </div>
    </section>
    <p class="wo-disclaimer">
      Primetime winners as of the 78th Emmys on September 14, 2026; Children's
      &amp; Family Emmys from March 2, 2026. Unlinked titles are editorial parent
      notes, not 1–5 transcript scores. Informal guidance — not an official
      ratings board. Your kids — your rules.
    </p>
  </main>
{faq_html(data["faqs"], section_id="faq")}"""


def write_emmys_2026_page(mixes: dict | None = None) -> list[tuple[str, str]]:
    """Render /emmys-2026. Returns sitemap (url, priority) tuples."""
    from build_web import SITE, WEB, _static_page, clip_meta, faq_jsonld

    mixes = mixes or {}
    data = page_data(mixes)
    url = f"{SITE}/{SLUG}"
    title = "2026 Emmys: What's OK to Watch With Kids"
    desc = clip_meta(
        "Widow's Bay won comedy — it's a horror show. The Muppet Show, Abbott Elementary, "
        "Sesame Street and Win or Lose are the 2026 Emmy titles actually OK with kids."
    )
    jsonld = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Article",
                "headline": title,
                "description": desc,
                "datePublished": UPDATED,
                "dateModified": UPDATED,
                "url": url,
                "image": f"{SITE}/covers/simpsons.jpg",
                "author": {"@id": f"{SITE}/#org"},
                "publisher": {"@id": f"{SITE}/#org"},
                "about": {
                    "@type": "Event",
                    "name": "78th Primetime Emmy Awards",
                    "startDate": "2026-09-14",
                    "location": "Los Angeles",
                },
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Shows", "item": f"{SITE}/"},
                    {"@type": "ListItem", "position": 2, "name": "Emmys 2026", "item": url},
                ],
            },
            faq_jsonld(data["faqs"]),
        ],
    }
    (WEB / f"{SLUG}.html").write_text(
        _static_page(
            url=url,
            title=title,
            desc=desc,
            image=f"{SITE}/covers/simpsons.jpg",
            css_href="friends.css",
            jsonld=jsonld,
            body=page_body(mixes),
            prefix="",
        )
    )
    print(f"Wrote {SLUG}.html")
    return [(url, "0.9")]
