#!/usr/bin/env python3
"""Weekly 'What's on' family-movie roundups. Regenerated by build_web.py."""

from __future__ import annotations

import html
from datetime import date
from pathlib import Path

_TODAY = date.today()
UPDATED = _TODAY.isoformat()
UPDATED_DISPLAY = _TODAY.strftime("%B %d, %Y").replace(" 0", " ")
REGION = "US"

# Evergreen slugs. Rewrite in place each Friday; do not date the URL.
HUB_SLUG = "whats-on"


def _esc(value) -> str:
    return html.escape(str(value or ""), quote=True)


SERVICES: list[dict] = [
    {
        "slug": "netflix-family-movies",
        "service": "Netflix",
        "short": "Netflix",
        "cover": "whats-on/dog-man.jpg",
        "h1": "Good Family Movies on Netflix Right Now",
        "title": "Good Family Movies on Netflix Right Now (September 18, 2026)",
        "desc": (
            "Newly added family movies on Netflix this month: Dog Man, Puss in Boots: "
            "The Last Wish, DreamWorks classics, plus what to skip. Updated September 18, 2026."
        ),
        "lede": (
            "Netflix dumped a stack of DreamWorks titles on September 1, then added the "
            "actually-good new ones later: <strong>Puss in Boots: The Last Wish</strong> on "
            "the 10th and <strong>Dog Man</strong> on the 13th. Tonight, pick from what "
            "landed this month — not the stale kids row."
        ),
        "tonight": (
            "<strong>Dog Man</strong> if they’re 6–10. <strong>Monster at the End of This "
            "Story</strong> if they’re preschool. <strong>Puss in Boots: The Last Wish</strong> "
            "only if 8+ can handle a wolf who is literally Death."
        ),
        "picks": [
            {
                "title": "Dog Man",
                "year": 2025,
                "mpaa": "PG",
                "image": "whats-on/dog-man.jpg",
                "added": "September 13",
                "ages": "6–10",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "The Dav Pilkey / DreamWorks movie finally hit the US Netflix kids row "
                    "this week. Half-dog, half-cop, all slapstick. Your kid already knows the "
                    "books; the film is the same energy — loud, goofy, slightly potty, never mean."
                ),
                "watch_for": [
                    "Cartoon fights and explosions",
                    "Bathroom / dog-behavior gags",
                    "A villain who wants to be loved more than feared",
                ],
            },
            {
                "title": "Puss in Boots: The Last Wish",
                "year": 2022,
                "mpaa": "PG",
                "image": "whats-on/puss-in-boots-the-last-wish.jpg",
                "added": "September 10",
                "ages": "8+",
                "verdict": "preview",
                "verdict_label": "Preview first",
                "why": (
                    "The best thing DreamWorks has made in years — and the one parents "
                    "underestimate. The wolf is Death. He is persistent, quiet, and designed "
                    "to scare. Fine for most 8–10s who already do Shrek; a hard pass for "
                    "sensitive six-year-olds."
                ),
                "watch_for": [
                    "A personification of Death who stalks Puss",
                    "Sword fights and a dark fairy-crime world",
                    "Panic-attack imagery when Puss hits his last life",
                ],
            },
            {
                "title": "Monster at the End of This Story",
                "year": 2026,
                "mpaa": "TV-Y",
                "image": "whats-on/monster-at-the-end-of-this-story.jpg",
                "added": "September 7",
                "ages": "2–6",
                "verdict": "play",
                "verdict_label": "Preschool pick",
                "why": (
                    "Sesame Street’s Grover-vs-the-last-page special. The whole joke is that "
                    "the monster is him. Short, musical, and the only September Netflix add "
                    "that is actually for toddlers."
                ),
                "watch_for": ["Mild pretend-scary buildup that resolves as a hug"],
            },
            {
                "title": "Barbie in the Nutcracker",
                "year": 2001,
                "mpaa": "G",
                "image": "whats-on/barbie-in-the-nutcracker.jpg",
                "added": "September 14",
                "ages": "4–8",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "The 2001 Clara-as-Barbie ballet movie, not a new theatrical. Mouse King, "
                    "Sugarplum Fairy, no innuendo. A calm Sunday-afternoon watch if Dog Man "
                    "is too shouty."
                ),
                "watch_for": ["A villain mouse army — cartoon, not nightmare fuel"],
            },
            {
                "title": "Robots",
                "year": 2005,
                "mpaa": "PG",
                "image": "whats-on/robots.jpg",
                "added": "September 16",
                "ages": "6–10",
                "verdict": "play",
                "verdict_label": "New this week",
                "why": (
                    "Blue Sky’s scrapyard adventure landed Wednesday. Ewan McGregor, Robin "
                    "Williams, a kid inventor who leaves home. Milder than Antz, funnier than "
                    "the trailer suggested in 2005."
                ),
                "watch_for": [
                    "Outdated-parts-as-euthanasia subtext if you squint",
                    "A few robot-body gags",
                    "Chase / chop sequences",
                ],
            },
            {
                "title": "Flushed Away",
                "year": 2006,
                "mpaa": "PG",
                "image": "whats-on/flushed-away.jpg",
                "added": "September 1",
                "ages": "6+",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "Aardman rats in a London sewer. Toilet humor is the premise, not a side "
                    "gag. The Toad is a cartoon tyrant; nothing here is meaner than a "
                    "Saturday-morning chase."
                ),
                "watch_for": ["Poop / flush jokes throughout", "Slapstick drowning scares"],
            },
            {
                "title": "Shark Tale",
                "year": 2004,
                "mpaa": "PG",
                "image": "whats-on/shark-tale.jpg",
                "added": "September 1",
                "ages": "7+",
                "verdict": "preview",
                "verdict_label": "Preview first",
                "why": (
                    "Will Smith as a hustler fish in a mob parody. Fine as a silly underwater "
                    "cartoon; the Godfather riffs and a few adult asides are why it isn’t the "
                    "preschool pick."
                ),
                "watch_for": [
                    "Mob-hit jokes (cartoon, not graphic)",
                    "Mild innuendo and booty gags",
                    "A character fakes another fish’s death for clout",
                ],
            },
            {
                "title": "Antz",
                "year": 1998,
                "mpaa": "PG",
                "image": "whats-on/antz.jpg",
                "added": "September 1",
                "ages": "8+",
                "verdict": "preview",
                "verdict_label": "Preview first",
                "why": (
                    "Woody Allen’s neurotic worker ant vs. a genocidal general. The war "
                    "termite battle is louder and darker than the insect-cute poster. Not "
                    "A Bug’s Life."
                ),
                "watch_for": [
                    "Insect-war carnage (stylized, still a battlefield)",
                    "A drowning / flood sequence",
                    "Adult one-liners aimed over kids’ heads",
                ],
            },
            {
                "title": "The Prince of Egypt",
                "year": 1998,
                "mpaa": "PG",
                "image": "whats-on/prince-of-egypt.jpg",
                "added": "September 1",
                "ages": "8+",
                "verdict": "preview",
                "verdict_label": "Preview first",
                "why": (
                    "The one September DreamWorks title that is actually great — and not a "
                    "cozy kids movie. Slavery, plagues, the death of the firstborn. Watch it "
                    "with them if you want the conversation. Do not dump it on a five-year-old "
                    "because it is animated."
                ),
                "watch_for": [
                    "Enslavement and beatings",
                    "Plagues, including the death of children",
                    "A drowning army in the Red Sea",
                ],
            },
            {
                "title": "The Flintstones",
                "year": 1994,
                "mpaa": "PG",
                "image": "whats-on/flintstones.jpg",
                "added": "September 1",
                "ages": "8+",
                "verdict": "preview",
                "verdict_label": "Preview first",
                "why": (
                    "Live-action John Goodman / Rick Moranis. Cartoon violence, workplace "
                    "scheming, and 90s innuendo. A nostalgia play for you, not a default for "
                    "little kids."
                ),
                "watch_for": ["Suggestive jokes", "Smoking / drinking gags", "A mistress subplot"],
            },
        ],
        "series": [
            {
                "title": "Pokémon Horizons: Season 3 — Rising Hope, Part 4",
                "image": "whats-on/pokemon-horizons.jpg",
                "added": "September 18",
                "note": (
                    "Today’s drop. New episodes, not a movie. If they still want the original "
                    "series, we rated <a href=\"/pokemon\">Pokémon: Indigo League</a> episode "
                    "by episode — almost entirely mild."
                ),
            },
            {
                "title": "Gabby’s Dollhouse, Season 14",
                "image": "whats-on/gabbys-dollhouse.jpg",
                "added": "September 14",
                "note": (
                    "Preschool cat-and-now-puppy playdate season. Fine in the background while "
                    "you cook. Not a movie night."
                ),
            },
            {
                "title": "Stranger Things: Tales From ’85, Season 2",
                "image": "whats-on/stranger-things-tales-from-85.jpg",
                "added": "September 17",
                "note": (
                    "Animated Hawkins is milder than the live-action show, but it is still "
                    "the Upside Down. We rated <a href=\"/stranger-things\">Stranger Things</a> "
                    "as mostly too much for younger kids — don’t assume the cartoon is a free pass."
                ),
            },
        ],
        "already": [
            {
                "title": "KPop Demon Hunters",
                "image": "kpop-demon-hunters.jpg",
                "href": "/kpop-demon-hunters",
                "note": (
                    "Still the Netflix original everyone is asking for. We scored the film from "
                    "the transcript as mild overall — demon battles and shame/fear themes are "
                    "the reason to preview if your kid startles easily."
                ),
            },
            {
                "title": "Pokémon: Indigo League",
                "image": "pokemon.jpg",
                "href": "/pokemon",
                "note": "79 episodes rated: almost all mild. Start here if Horizons feels too new.",
            },
        ],
        "skip": [
            {
                "title": "Jaws 1–3 (+ The Revenge)",
                "why": "Rated R / PG shark-attack movies. On the September 1 dump. Not family.",
            },
            {
                "title": "17 Again",
                "why": "PG-13 body-swap teen comedy. Fine for teens, not a family movie night.",
            },
            {
                "title": "Big Daddy",
                "why": "PG-13 Sandler. Bathroom humor plus adult sex jokes. Skip with little kids.",
            },
            {
                "title": "Uncle Buck",
                "why": (
                    "John Candy is lovely. The movie still has swearing, smoking, and a "
                    "teen-dating plot that is not for the elementary couch."
                ),
            },
            {
                "title": "Neighbors, Ready or Not, Knocked Up…",
                "why": (
                    "The rest of the September 1 licensed haul is adult comedy and horror. "
                    "If it isn’t animated and isn’t Sesame, assume skip."
                ),
            },
        ],
        "coming": [
            {
                "when": "September 23",
                "title": "Wonka’s The Golden Ticket",
                "image": "whats-on/wonkas-the-golden-ticket.jpg",
                "note": "Reality competition in a chocolate factory — not a kids movie.",
            },
            {
                "when": "September 24",
                "title": "A Magnificent Life",
                "image": "whats-on/a-magnificent-life.jpg",
                "note": (
                    "Sylvain Chomet adult animation about a filmmaker. Do not confuse with a "
                    "family cartoon."
                ),
            },
            {
                "when": "September 29",
                "title": "LEGO One Piece",
                "image": "whats-on/lego-one-piece.jpg",
                "note": "Two-part animated special. Milder pirate cartoon than the live-action.",
            },
            {
                "when": "September 30",
                "title": "Thomas & Friends: Really Helpful Engines",
                "image": "whats-on/thomas-really-helpful-engines.jpg",
                "note": "Preschool movie for the train kids.",
            },
        ],
        "video": {
            "title": "Good Family Movies on Netflix Right Now (Sept 18, 2026)",
            "hook": "Netflix added Dog Man this week. Here’s what is actually fine for kids — and what isn’t.",
            "script": (
                "Netflix just restocked the kids row. Three that landed this month: Dog Man, "
                "September 13 — slapstick, potty jokes, great for 6 to 10. Puss in Boots The "
                "Last Wish, September 10 — stunning, but the wolf is Death. Preview if they’re "
                "under 8. And Monster at the End of This Story for preschool, Grover, seven "
                "minutes of fake-scary. Skip Jaws, skip 17 Again, skip Uncle Buck even though "
                "the poster looks cozy. Full list with ages is on Watch With The Kids."
            ),
            "onscreen": [
                "Dog Man — 6–10 — PLAY",
                "Puss in Boots: The Last Wish — 8+ — PREVIEW (Death wolf)",
                "Monster at the End of This Story — 2–6 — PLAY",
                "Skip: Jaws, 17 Again, Big Daddy, Uncle Buck",
            ],
            "cta": "watchwiththekids.com/whats-on/netflix-family-movies",
        },
        "faqs": [
            (
                "What is the best new family movie on Netflix right now?",
                "As of September 18, 2026: <strong>Dog Man</strong> for elementary, "
                "<strong>Puss in Boots: The Last Wish</strong> for 8+, and "
                "<strong>Monster at the End of This Story</strong> for preschool.",
            ),
            (
                "Is Puss in Boots: The Last Wish too scary?",
                "Often, yes, for under-8s. The wolf is a personification of Death. Older "
                "elementary kids who already watch Shrek usually handle it.",
            ),
            (
                "Are Antz and The Prince of Egypt okay for little kids because they’re animated?",
                "No. Antz is a war movie with insects. The Prince of Egypt includes slavery "
                "and the death of firstborn children. Both are PG for a reason.",
            ),
            (
                "Do you rate every Netflix movie episode by episode?",
                "We rate shows and films we have transcripts for — including "
                '<a href="/kpop-demon-hunters">KPop Demon Hunters</a> and '
                '<a href="/pokemon">Pokémon: Indigo League</a>. This What’s on list is a '
                "weekly parent pass over <em>newly added</em> titles.",
            ),
        ],
    },
    {
        "slug": "disney-plus-family-movies",
        "service": "Disney+",
        "short": "Disney+",
        "cover": "clone-wars.jpg",
        "h1": "Good Family Movies on Disney+ Right Now",
        "title": "Good Family Movies on Disney+ Right Now (September 18, 2026)",
        "desc": (
            "Newly added on Disney+ this month: The Mandalorian and Grogu, LEGO Star Wars: "
            "The Mandalorian, with Toy Story 5 arriving September 23. Updated September 18, 2026."
        ),
        "lede": (
            "Disney+ actually shipped a new theatrical this month: "
            "<strong>The Mandalorian and Grogu</strong> arrived September 2 with a LEGO "
            "companion special. <strong>Toy Story 5</strong> is five days out. The rest of "
            "the family shelf is the catalog you already pay for — Pixar, Marvel kids, "
            "Clone Wars."
        ),
        "tonight": (
            "<strong>LEGO Star Wars: The Mandalorian</strong> if you want Grogu without "
            "blaster-realism. The live-action movie if they’re already in the show. Wait "
            "until the 23rd for Toy Story 5."
        ),
        "picks": [
            {
                "title": "LEGO Star Wars: The Mandalorian",
                "year": 2026,
                "image": "whats-on/lego-star-wars-the-mandalorian.jpg",
                "mpaa": "TV-Y7",
                "added": "September 2",
                "ages": "5–10",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "The brick special that landed with the movie. Recasts a lot of the "
                    "live-action beats as slapstick. Pedro Pascal is not Din here — it’s a "
                    "LEGO voice cast — which is the point. This is the Grogu watch if live "
                    "Mandalorian still feels like a Western."
                ),
                "watch_for": ["Cartoon blasters and comic falls", "Cameos of characters who die in the show, played for gags"],
            },
            {
                "title": "The Mandalorian and Grogu",
                "year": 2026,
                "image": "whats-on/the-mandalorian-and-grogu.jpg",
                "mpaa": "PG",
                "added": "September 2",
                "ages": "8+",
                "verdict": "preview",
                "verdict_label": "Preview first",
                "why": (
                    "The May theatrical, now on the service that made the show. Same rules as "
                    "the series: bounty-hunter violence, Grogu in danger, a Hutt plot. Cute "
                    "baby, not a baby movie. If they watch The Mandalorian already, this is "
                    "the obvious Friday night."
                ),
                "watch_for": [
                    "Shootouts and creature attacks",
                    "Grogu in peril (the emotional hook)",
                    "Fantasy violence at a PG, not G, level",
                ],
            },
        ],
        "series": [],
        "already": [
            {
                "title": "Star Wars: The Clone Wars",
                "image": "clone-wars.jpg",
                "href": "/clone-wars",
                "note": (
                    "133 episodes we rated: 90% mild. Better weeknight TV than putting on "
                    "Revenge of the Sith because the movie is ‘the one with the clones.’"
                ),
            },
            {
                "title": "Phineas and Ferb, Gravity Falls, Amphibia, The Owl House",
                "image": "phineas-and-ferb.jpg",
                "href": "/guides/",
                "note": "All scored episode by episode. Gravity Falls and Owl House need a preview on the spookier eps.",
            },
        ],
        "skip": [
            {
                "title": "Andor, The Acolyte, adult Marvel",
                "why": "On the same app. Not family just because the logo is a mouse.",
            },
        ],
        "coming": [
            {
                "when": "September 23",
                "title": "Toy Story 5",
                "image": "whats-on/toy-story-5.jpg",
                "note": (
                    "Woody, Buzz, Jessie vs. new tech in Bonnie’s house. The actual family "
                    "event of the month. We’ll refresh this page when it lands."
                ),
            },
        ],
        "video": {
            "title": "Good Family Movies on Disney+ Right Now (Sept 18, 2026)",
            "hook": "Mandalorian and Grogu is on Disney+ — but the LEGO version is the one for little kids.",
            "script": (
                "Two Star Wars drops on September 2. LEGO Star Wars The Mandalorian — brick "
                "gags, fine for 5 to 10. The live-action Mandalorian and Grogu movie — PG, "
                "blasters, Grogu in danger, better for 8 plus. Toy Story 5 hits Disney+ "
                "September 23. That’s the one to hold the popcorn for. Full parent notes on "
                "Watch With The Kids."
            ),
            "onscreen": [
                "LEGO Star Wars: The Mandalorian — 5–10 — PLAY",
                "The Mandalorian and Grogu — 8+ — PREVIEW",
                "Toy Story 5 — September 23",
            ],
            "cta": "watchwiththekids.com/whats-on/disney-plus-family-movies",
        },
        "faqs": [
            (
                "Is The Mandalorian and Grogu okay for young kids?",
                "If they already watch the show, probably. It is PG space-western violence, "
                "not a preschool Grogu cartoon. Use the LEGO special for under-8s.",
            ),
            (
                "When is Toy Story 5 on Disney+?",
                "September 23, 2026 — five days from this update.",
            ),
        ],
    },
    {
        "slug": "prime-video-family-movies",
        "service": "Prime Video",
        "short": "Prime Video",
        "cover": "spongebob.jpg",
        "h1": "Good Family Movies on Prime Video Right Now",
        "title": "Good Family Movies on Prime Video Right Now (September 18, 2026)",
        "desc": (
            "Newly added family movies on Prime Video this month: Ice Age and Ice Age: Dawn "
            "of the Dinosaurs (September 1). Updated September 18, 2026."
        ),
        "lede": (
            "Prime’s September 1 licensed drop is mostly thrillers. Buried in it: two "
            "<strong>Ice Age</strong> movies that actually work for a family couch. "
            "SpongeBob’s latest theatrical is on Paramount+, not included with Prime."
        ),
        "tonight": (
            "<strong>Ice Age</strong> (2002) for a gentle prehistoric hang. "
            "<strong>Dawn of the Dinosaurs</strong> if they can handle louder dino-peril."
        ),
        "picks": [
            {
                "title": "Ice Age",
                "year": 2002,
                "image": "whats-on/ice-age.jpg",
                "mpaa": "PG",
                "added": "September 1",
                "ages": "5–10",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "Manny, Sid, Diego, the baby. The saddest beat is a mother pushing her "
                    "child to safety — short, not gory. Scrat is the whole joke. This is the "
                    "one September Prime add that is actually a family movie."
                ),
                "watch_for": ["A parent’s death implied in the opening", "Cartoon chases and a tiger reveal"],
            },
            {
                "title": "Ice Age: Dawn of the Dinosaurs",
                "year": 2009,
                "image": "whats-on/ice-age-dawn-of-the-dinosaurs.jpg",
                "mpaa": "PG",
                "added": "September 1",
                "ages": "6–11",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "The third film, dinosaurs underground. Bigger set pieces than the first. "
                    "Still a kids adventure, not Jurassic Park."
                ),
                "watch_for": ["Dinosaur hunts and falls", "A baby-dino subplot with mild peril"],
            },
        ],
        "series": [],
        "already": [
            {
                "title": "The SpongeBob Movie: Search for SquarePants",
                "image": "whats-on/spongebob-search-for-squarepants.jpg",
                "href": "/spongebob",
                "note": (
                    "On Prime as a rental, not as a Prime-included title. Stream it on "
                    "Paramount+ instead. We rated 602 SpongeBob episodes as 100% mild if you "
                    "want the series."
                ),
            },
        ],
        "skip": [
            {
                "title": "Cape Fear, Halloween II, The Purge, Carrie…",
                "why": "The rest of Prime’s September 1 list. Horror and crime. Not a kids row.",
            },
            {
                "title": "Teen Wolf / The Love Hypothesis",
                "why": "Teen and adult romance. Love Hypothesis (Sep 23) is BookTok, not Bluey.",
            },
        ],
        "coming": [
            {
                "when": "September 23",
                "title": "The Love Hypothesis",
                "image": "whats-on/the-love-hypothesis.jpg",
                "note": "Adult rom-com. Do not add it to the kids profile because it is ‘new.’",
            },
        ],
        "video": {
            "title": "Good Family Movies on Prime Video Right Now (Sept 18, 2026)",
            "hook": "Prime added two Ice Age movies on September 1. Almost everything else it added is horror.",
            "script": (
                "Prime Video’s September drop looks huge until you filter for kids. Keep Ice "
                "Age from 2002 — gentle, one sad mom beat. Keep Dawn of the Dinosaurs if they "
                "like louder chases. Skip Cape Fear, skip Halloween, skip The Purge. SpongeBob "
                "Search for SquarePants is Paramount Plus, not included with Prime. List is on "
                "Watch With The Kids."
            ),
            "onscreen": [
                "Ice Age (2002) — 5–10 — PLAY",
                "Ice Age: Dawn of the Dinosaurs — 6–11 — PLAY",
                "Skip: Prime’s horror dump",
            ],
            "cta": "watchwiththekids.com/whats-on/prime-video-family-movies",
        },
        "faqs": [
            (
                "What new family movies are on Prime Video in September 2026?",
                "The clear ones: <strong>Ice Age</strong> and <strong>Ice Age: Dawn of the "
                "Dinosaurs</strong>, both added September 1 with a Prime membership.",
            ),
            (
                "Is the new SpongeBob movie on Prime?",
                "You can rent it there. It streams with a subscription on Paramount+.",
            ),
        ],
    },
    {
        "slug": "max-family-movies",
        "service": "Max",
        "short": "Max",
        "cover": "adventure-time.jpg",
        "h1": "Good Family Movies on Max Right Now",
        "title": "Good Family Movies on Max Right Now (September 18, 2026)",
        "desc": (
            "Newly added family titles on Max this month: Horton Hears a Who!, plus Krypto, "
            "Batwheels, and Teen Titans Go. September’s movie dump is mostly horror. Updated "
            "September 18, 2026."
        ),
        "lede": (
            "Max’s September 1 movie dump is a horror aisle with one kids title hiding in it: "
            "<strong>Dr. Seuss’ Horton Hears a Who!</strong> The actually-new-for-kids stuff "
            "this month is Cartoon Network episodes — Krypto, Batwheels, Teen Titans Go. "
            "Ghibli and Harry Potter films are still the reason the kids profile exists."
        ),
        "tonight": (
            "<strong>Horton Hears a Who!</strong> if you want a real movie. "
            "<strong>Krypto Saves the Day</strong> (new season pieces from Sep 10) for "
            "preschool. Studio Ghibli if they’re old enough for spirits and sadness."
        ),
        "picks": [
            {
                "title": "Dr. Seuss’ Horton Hears a Who!",
                "year": 2008,
                "image": "whats-on/horton-hears-a-who.jpg",
                "mpaa": "G",
                "added": "September 1",
                "ages": "4–9",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "Jim Carrey as Horton, the speck, ‘a person’s a person.’ The one family "
                    "feature in Max’s enormous September 1 licensed drop. Kind, loud, no "
                    "jump scares."
                ),
                "watch_for": ["A mob almost boils the clover — cartoon peril", "Carrey volume"],
            },
        ],
        "series": [
            {
                "title": "Krypto Saves the Day, Season 2A",
                "image": "whats-on/krypto-saves-the-day.jpg",
                "added": "September 10",
                "note": "Preschool Superman’s dog. New batch this month.",
            },
            {
                "title": "Batwheels, Season 3E",
                "image": "whats-on/batwheels.jpg",
                "added": "September 19",
                "note": "Tomorrow. Talking Bat-vehicles. Fine for 4–7.",
            },
            {
                "title": "Teen Titans Go!, Season 9H",
                "image": "whats-on/teen-titans-go.jpg",
                "added": "September 20",
                "note": "Gag cartoon. Harmless, exhausting, not a movie.",
            },
        ],
        "already": [
            {
                "title": "Studio Ghibli library",
                "image": "whats-on/totoro.jpg",
                "href": "/guides/",
                "note": (
                    "Totoro and Ponyo for little kids. Spirited Away and The Boy and the Heron "
                    "for 10+ who can sit with grief. Max still has the US streaming deal."
                ),
            },
            {
                "title": "Harry Potter films",
                "image": "whats-on/harry-potter-philosophers-stone.jpg",
                "href": "/guides/",
                "note": (
                    "The eight movies, not the HBO series (that’s Christmas 2026). Philosopher’s "
                    "Stone / Sorcerer’s Stone is the family entry; the later films get darker."
                ),
            },
            {
                "title": "Adventure Time",
                "image": "adventure-time.jpg",
                "href": "/adventure-time",
                "note": "236 episodes rated, 95% mild. Better weeknight than putting on Beetlejuice because it ‘looked cartoony.’",
            },
        ],
        "skip": [
            {
                "title": "Beetlejuice, Gremlins, Carrie, Misery, The Craft…",
                "why": "The September 1 drop. Some are cult-family in adult memory. None are for little kids tonight.",
            },
            {
                "title": "The Meg (Sep 23) and Backrooms (Sep 25)",
                "why": "Shark PG-13 and A24 horror. Coming later this month. Not a maybe.",
            },
        ],
        "coming": [
            {
                "when": "September 27",
                "title": "Totally Spies, Season 7C",
                "image": "whats-on/totally-spies.jpg",
                "note": "Tween spy cartoon. Milder than it looks.",
            },
            {
                "when": "Christmas 2026",
                "title": "Harry Potter (HBO series)",
                "image": "whats-on/harry-potter-hbo.jpg",
                "note": "Not out. Do not search for it in the app yet.",
            },
        ],
        "video": {
            "title": "Good Family Movies on Max Right Now (Sept 18, 2026)",
            "hook": "Max added a mountain of movies on September 1. One of them is for kids.",
            "script": (
                "Horton Hears a Who is the family movie in Max’s September dump. Everything "
                "around it is Beetlejuice, Gremlins, Carrie. For little kids this week: Krypto "
                "Saves the Day, new episodes September 10. For a real film night, stay on the "
                "Ghibli row or the first Harry Potter. Skip The Meg next week. Details on "
                "Watch With The Kids."
            ),
            "onscreen": [
                "Horton Hears a Who! — 4–9 — PLAY",
                "Krypto Saves the Day — preschool",
                "Skip: Beetlejuice, Gremlins, The Meg, Backrooms",
            ],
            "cta": "watchwiththekids.com/whats-on/max-family-movies",
        },
        "faqs": [
            (
                "Did Max add Harry Potter this month?",
                "The films are already on Max. The new HBO series premieres Christmas 2026, "
                "not September.",
            ),
            (
                "Is Beetlejuice a family movie?",
                "PG, ghoulish, and a bad surprise for a six-year-old. Not on this list.",
            ),
        ],
    },
    {
        "slug": "apple-tv-family-movies",
        "service": "Apple TV+",
        "short": "Apple TV+",
        "cover": "ted-lasso.jpg",
        "h1": "Good Family Movies on Apple TV+ Right Now",
        "title": "Good Family Movies on Apple TV+ Right Now (September 18, 2026)",
        "desc": (
            "Apple TV+ in September 2026 is stacked with adult originals. The family shelf is "
            "Peanuts, Interrupting Chicken, and kids series — plus why Ted Lasso is a skip. "
            "Updated September 18, 2026."
        ),
        "lede": (
            "Apple’s September slate is <em>Mayday</em>, <em>Slow Horses</em>, "
            "<em>Last Seen</em>, and new <strong>Ted Lasso</strong> — none of that is family. "
            "The kids row is still the Peanuts deal: last month’s "
            "<strong>Snoopy Presents: There’s No Place Like Home, Snoopy</strong> plus the "
            "classic specials. That is the family movie night. Do not let the ‘new this week’ "
            "rail autoplay Lasso."
        ),
        "tonight": (
            "<strong>There’s No Place Like Home, Snoopy</strong> (July 31 special, still the "
            "freshest Peanuts film). Then a classic: It’s the Great Pumpkin if you want "
            "October early."
        ),
        "picks": [
            {
                "title": "Snoopy Presents: There’s No Place Like Home, Snoopy",
                "year": 2026,
                "image": "whats-on/snoopy-no-place-like-home.jpg",
                "mpaa": "TV-G",
                "added": "July 31 (still the new one)",
                "ages": "4–10",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "Snoopy’s doghouse gets sold at a yard sale. Charlie Brown tries to get it "
                    "back. TV-G, no jump scares, the only 2026 Apple original that is actually "
                    "a kids movie. September didn’t add a new family feature — this is still "
                    "the one."
                ),
                "watch_for": ["Mild sadness when the house is gone", "A search-adventure, not peril"],
            },
        ],
        "series": [
            {
                "title": "Interrupting Chicken, Camp Snoopy, Shape Island, Wonder Pets: In the City",
                "image": "whats-on/interrupting-chicken.jpg",
                "added": "On the kids tab now",
                "note": "Apple’s actual kids slate. None of them premiered this week; they’re the reliable shelf.",
            },
        ],
        "already": [
            {
                "title": "Ted Lasso (Season 4, in progress)",
                "image": "ted-lasso.jpg",
                "href": "/ted-lasso",
                "note": (
                    "New episodes this month. We rated 40 episodes: 100% too much for younger "
                    "kids — language, sex talk, adult crises. Great show. Not family night."
                ),
            },
        ],
        "skip": [
            {
                "title": "Mayday (Sep 4), Slow Horses S6, Last Seen, Brothers",
                "why": "September’s Apple Originals. Crime, spies, missing-kid adult drama. Keep them off the kids profile.",
            },
        ],
        "coming": [
            {
                "when": "Later in 2026",
                "title": "Snoopy Unleashed (feature, in production)",
                "image": "whats-on/snoopy-unleashed.jpg",
                "note": "Not out. Don’t search the app for it yet.",
            },
        ],
        "video": {
            "title": "Good Family Movies on Apple TV+ Right Now (Sept 18, 2026)",
            "hook": "Apple TV+ looks full this month. Almost none of it is for kids.",
            "script": (
                "Apple’s September originals are Ted Lasso, Slow Horses, Mayday. We rated Ted "
                "Lasso — too much for younger kids, every episode. For actual family: Snoopy "
                "Presents There’s No Place Like Home, still the 2026 kids movie, plus the "
                "Peanuts library. That is the list. Watch With The Kids has the parent notes."
            ),
            "onscreen": [
                "Snoopy Presents — TV-G — PLAY",
                "Ted Lasso — SKIP with little kids",
                "Mayday / Slow Horses — adult",
            ],
            "cta": "watchwiththekids.com/whats-on/apple-tv-family-movies",
        },
        "faqs": [
            (
                "Did Apple add a new family movie in September 2026?",
                "No theatrical-style kids movie this month. The newest family film on the "
                "service is still the July 31 Snoopy Presents special.",
            ),
            (
                "Can kids watch Ted Lasso because it’s on Apple TV+?",
                "No. Our episode scores are 4–5 across the catalog. Watch it after bedtime.",
            ),
        ],
    },
    {
        "slug": "paramount-plus-family-movies",
        "service": "Paramount+",
        "short": "Paramount+",
        "cover": "spongebob.jpg",
        "h1": "Good Family Movies on Paramount+ Right Now",
        "title": "Good Family Movies on Paramount+ Right Now (September 18, 2026)",
        "desc": (
            "Newly added on Paramount+ this month: Clash of the Thundermans (September 3). "
            "SpongeBob: Search for SquarePants is already on the service. Updated September 18, 2026."
        ),
        "lede": (
            "Nickelodeon still lives here. The new-this-month title is "
            "<strong>Clash of the Thundermans</strong> (September 3). The better movie is "
            "already on the service: <strong>The SpongeBob Movie: Search for SquarePants</strong>. "
            "PAW Patrol: The Dino Movie is still theatrical / digital — not the app yet."
        ),
        "tonight": (
            "<strong>Search for SquarePants</strong> for almost any elementary kid. "
            "<strong>Clash of the Thundermans</strong> if they already watch the live-action "
            "Nick sitcom."
        ),
        "picks": [
            {
                "title": "Clash of the Thundermans",
                "year": 2026,
                "image": "whats-on/clash-of-the-thundermans.jpg",
                "mpaa": "TV-G",
                "added": "September 3",
                "ages": "6–12",
                "verdict": "play",
                "verdict_label": "New this month",
                "why": (
                    "Live-action Nick movie: Chloe’s new power, the Hero League wants boarding "
                    "school, the family splits. Superhero sitcom volume, not MCU carnage. "
                    "Only a win if they already like The Thundermans; otherwise it is lore."
                ),
                "watch_for": [
                    "Family-argument tension (nobody dies)",
                    "Cartoon energy super-fights",
                    "A kid being sent away — emotional, not scary",
                ],
            },
            {
                "title": "The SpongeBob Movie: Search for SquarePants",
                "year": 2025,
                "image": "whats-on/spongebob-search-for-squarepants.jpg",
                "mpaa": "PG",
                "added": "February 17 (still the one to play)",
                "ages": "5–10",
                "verdict": "play",
                "verdict_label": "Play tonight",
                "why": (
                    "SpongeBob vs. the Flying Dutchman, Mark Hamill voicing the ghost pirate. "
                    "Underworld quest, still a SpongeBob movie. We rated the series 602 "
                    "episodes, all mild — the film is the same universe, slightly bigger "
                    "set pieces."
                ),
                "watch_for": ["Ghost-pirate spookiness (comic)", "Underworld imagery, not horror"],
                "catalog": "/spongebob",
            },
        ],
        "series": [],
        "already": [
            {
                "title": "SpongeBob SquarePants (series)",
                "image": "spongebob.jpg",
                "href": "/spongebob",
                "note": "602 episodes rated: 100% mild. If the movie is a hit, stay on the series.",
            },
        ],
        "skip": [
            {
                "title": "Scary Movie (2026) — September 3",
                "why": "Same-day drop as Thundermans. Horror parody, R-adjacent gags. Keep it off the kids profile.",
            },
        ],
        "coming": [
            {
                "when": "Likely mid-October",
                "title": "PAW Patrol: The Dino Movie",
                "image": "whats-on/paw-patrol-dino.jpg",
                "note": (
                    "Still in theaters as of mid-August; digital purchase exists, Paramount+ "
                    "date not posted. Don’t promise it this week."
                ),
            },
        ],
        "video": {
            "title": "Good Family Movies on Paramount+ Right Now (Sept 18, 2026)",
            "hook": "Paramount+ added Clash of the Thundermans. The better family movie was already there.",
            "script": (
                "New on Paramount Plus September 3: Clash of the Thundermans — live-action Nick, "
                "fine if they already watch the show. The movie to actually put on: SpongeBob "
                "Search for SquarePants. PAW Patrol Dino Movie is not on the app yet. Skip the "
                "new Scary Movie, it landed the same day. Parent list on Watch With The Kids."
            ),
            "onscreen": [
                "Clash of the Thundermans — 6–12 — PLAY if they know the show",
                "SpongeBob: Search for SquarePants — 5–10 — PLAY",
                "Skip: Scary Movie (2026)",
            ],
            "cta": "watchwiththekids.com/whats-on/paramount-plus-family-movies",
        },
        "faqs": [
            (
                "What new family movie is on Paramount+ this month?",
                "<strong>Clash of the Thundermans</strong>, September 3. The strongest family "
                "feature on the service remains <strong>The SpongeBob Movie: Search for SquarePants</strong>.",
            ),
            (
                "Is PAW Patrol: The Dino Movie on Paramount+?",
                "Not yet. It’s in theaters / on digital; the streaming date has not been posted.",
            ),
        ],
    },
]


def service_by_slug(slug: str) -> dict | None:
    for s in SERVICES:
        if s["slug"] == slug:
            return s
    return None


def _verdict_class(verdict: str) -> str:
    if verdict == "play":
        return "play"
    if verdict == "skip":
        return "skip"
    return "preview"


COVERS = Path(__file__).resolve().parent / "web" / "covers"


def _poster_img(path: str, alt: str = "") -> str:
    return (
        f'<img class="wo-poster" src="../covers/{_esc(path)}" '
        f'alt="{_esc(alt)}" width="260" height="390" loading="lazy" decoding="async" />'
    )


def _card(inner: str, image: str | None, cls: str = "") -> str:
    classes = " ".join(x for x in (cls, "has-poster" if image else "") if x)
    poster = _poster_img(image) if image else ""
    return f"""    <article class="wo-pick {classes}">
      {poster}
      <div class="wo-pick-body">
      {inner}
      </div>
    </article>"""


def _cards_section(heading: str, cards: list[str]) -> str:
    if not cards:
        return ""
    return f"""    <section class="wo-section">
      <h2>{_esc(heading)}</h2>
      <div class="wo-picks">
{chr(10).join(cards)}
      </div>
    </section>"""


def _pick_html(pick: dict) -> str:
    chips = "".join(
        f'<li>{_esc(item)}</li>' for item in pick.get("watch_for") or []
    )
    watch = (
        f'<p class="wo-watch-label">Watch for</p><ul class="wo-watch">{chips}</ul>'
        if chips
        else ""
    )
    catalog = ""
    if pick.get("catalog"):
        catalog = (
            f'<p class="wo-catalog">Episode scores: '
            f'<a href="{_esc(pick["catalog"])}">open the show page</a>.</p>'
        )
    extra = watch + catalog
    inner = f"""<header class="wo-pick-head">
        <p class="wo-verdict">{_esc(pick["verdict_label"])}</p>
        <h3>{_esc(pick["title"])} <span>({_esc(pick["year"])})</span></h3>
        <p class="wo-meta">{_esc(pick["mpaa"])} · Added {_esc(pick["added"])} · Best for {_esc(pick["ages"])}</p>
      </header>
      <p>{pick["why"]}</p>
      {extra}"""
    return _card(inner, pick.get("image"), _verdict_class(pick["verdict"]))


def _series_section(items: list[dict]) -> str:
    cards = []
    for item in items:
        inner = f"""<header class="wo-pick-head">
        <p class="wo-verdict">New series</p>
        <h3>{_esc(item["title"])}</h3>
        <p class="wo-meta">Added {_esc(item["added"])}</p>
      </header>
      <p>{item["note"]}</p>"""
        cards.append(_card(inner, item.get("image")))
    return _cards_section("New series (not movies)", cards)


def _already_section(items: list[dict]) -> str:
    cards = []
    for item in items:
        name = (
            f'<a href="{_esc(item["href"])}">{_esc(item["title"])}</a>'
            if item.get("href")
            else _esc(item["title"])
        )
        inner = f"""<header class="wo-pick-head">
        <p class="wo-verdict">Already on</p>
        <h3>{name}</h3>
      </header>
      <p>{item["note"]}</p>"""
        cards.append(_card(inner, item.get("image")))
    return _cards_section("Already on — we rated these", cards)


def _coming_section(items: list[dict]) -> str:
    cards = []
    for item in items:
        inner = f"""<header class="wo-pick-head">
        <p class="wo-verdict">{_esc(item["when"])}</p>
        <h3>{_esc(item["title"])}</h3>
      </header>
      <p>{item["note"]}</p>"""
        cards.append(_card(inner, item.get("image")))
    return _cards_section("Coming later this month", cards)


def _list_block(title: str, items: list[dict], key_title: str, key_body: str) -> str:
    if not items:
        return ""
    rows = "\n".join(
        f"      <li><strong>{_esc(item[key_title])}</strong> — {item[key_body]}</li>"
        for item in items
    )
    return f"""    <section class="wo-section">
      <h2>{_esc(title)}</h2>
      <ul class="wo-plain">
{rows}
      </ul>
    </section>"""


def _require_posters() -> None:
    missing = []
    for svc in SERVICES:
        for group in ("picks", "series", "already", "coming"):
            for item in svc.get(group) or []:
                img = item.get("image")
                if not img:
                    missing.append(f"{svc['slug']} {group}: {item['title']}")
                elif not (COVERS / img).is_file():
                    missing.append(f"missing file {img} ({item['title']})")
    if missing:
        raise SystemExit("What's on posters missing:\n  " + "\n  ".join(missing))


SERVICE_ICONS = {
    "netflix-family-movies": ("netflix", "netflix.svg"),
    "disney-plus-family-movies": ("disney", "disney.svg"),
    "prime-video-family-movies": ("amazon", "amazon.svg"),
    "max-family-movies": ("max", "max.svg"),
    "apple-tv-family-movies": ("apple", "apple.svg"),
    "paramount-plus-family-movies": ("paramount", "paramount.svg"),
}


def _service_nav(current: str | None = None) -> str:
    links = []
    for s in SERVICES:
        cls = ' class="is-current"' if s["slug"] == current else ""
        provider, icon = SERVICE_ICONS[s["slug"]]
        links.append(
            f'<a href="/whats-on/{_esc(s["slug"])}"{cls} data-provider="{provider}" '
            f'aria-label="{_esc(s["short"])}">'
            f'<img class="wo-svc-logo" src="../icons/{icon}" alt="" width="24" height="16" />'
            f'<span>{_esc(s["short"])}</span></a>'
        )
    label = "Other guides" if current else "Streaming services"
    kicker = '<p class="wo-services-kicker">Other guides:</p>' if current else ""
    return f'<nav class="wo-services" aria-label="{label}">{kicker}' + "".join(links) + "</nav>"


def article_body(svc: dict) -> str:
    picks = "\n".join(_pick_html(p) for p in svc["picks"])
    series = _series_section(svc.get("series") or [])
    already = _already_section(svc.get("already") or [])
    skip = _list_block("On the service, not for family night", svc.get("skip") or [], "title", "why")
    coming = _coming_section(svc.get("coming") or [])
    from build_web import faq_html

    return f"""  <nav class="topnav wrap">
    <a class="back-home" href="/whats-on/">← What's on</a>
    <a class="back-home subtle" href="/emmys-2026">Emmys 2026</a>
    <a class="back-home subtle" href="/guides/">What to watch</a>
  </nav>
  <header class="hero wo-hero">
    <div class="wrap hero-inner">
      <div class="hero-copy">
        <p class="eyebrow">What's on · {_esc(svc["service"])} · {REGION} · {UPDATED_DISPLAY}</p>
        <h1>{_esc(svc["h1"])} ({UPDATED_DISPLAY})</h1>
        <p class="tagline">{svc["lede"]}</p>
        <p class="wo-updated">Updated {UPDATED_DISPLAY}.</p>
      </div>
    </div>
  </header>
  <main class="wrap wo-page">
    {_service_nav(svc["slug"])}
    <aside class="wo-tonight">
      <p class="wo-tonight-kicker">Tonight</p>
      <p>{svc["tonight"]}</p>
    </aside>
    <section class="wo-section">
      <h2>Newly added — start here</h2>
      <div class="wo-picks">
{picks}
      </div>
    </section>
{series}
{already}
{skip}
{coming}
    <p class="wo-disclaimer">
      Catalog is {REGION} {_esc(svc["service"])} as of {UPDATED_DISPLAY}. Titles move by
      country and can vanish without notice. Informal parent guidance — not an official
      ratings board. Your kids — your rules.
    </p>
  </main>
{faq_html(svc["faqs"])}"""


def hub_body() -> str:
    cards = []
    for s in SERVICES:
        first_pick = s["picks"][0] if s["picks"] else None
        first = first_pick["title"] if first_pick else s["service"]
        cover = (first_pick or {}).get("image") or s.get("cover") or ""
        provider, icon = SERVICE_ICONS[s["slug"]]
        thumb = (
            f'<span class="wo-hub-cover" aria-hidden="true">'
            f'<img src="../covers/{_esc(cover)}" alt="" width="400" height="225" '
            f'loading="lazy" decoding="async" />'
            f"</span>"
            if cover
            else ""
        )
        cards.append(
            f'<li><a class="wo-hub-card" href="/whats-on/{_esc(s["slug"])}" '
            f'data-provider="{provider}">'
            f"{thumb}"
            f'<span class="wo-hub-body">'
            f'<span class="wo-hub-svc">'
            f'<img class="wo-svc-logo" src="../icons/{icon}" alt="" width="24" height="16" />'
            f'<span>{_esc(s["short"])}</span></span>'
            f"<strong>{_esc(s['h1'])}</strong>"
            f'<span class="wo-hub-pick">Tonight: {_esc(first)}</span>'
            f"</span></a></li>"
        )
    return f"""  <nav class="topnav wrap">
    <a class="back-home" href="/">← All shows</a>
    <a class="back-home subtle" href="/emmys-2026">Emmys 2026</a>
    <a class="back-home subtle" href="/guides/">What to watch</a>
  </nav>
  <header class="hero wo-hero">
    <div class="wrap hero-inner">
      <div class="hero-copy">
        <p class="eyebrow">Weekly · Newly added · Six streamers</p>
        <h1>What's on</h1>
        <p class="tagline">
          Family movies that <em>just landed</em> on Netflix, Disney+, Prime Video, Max,
          Apple TV+ and Paramount+ — with the titles that only look kid-friendly stripped out.
        </p>
        <p class="wo-updated">Updated {UPDATED_DISPLAY}. We refresh every Friday.</p>
        <p class="wo-inline-banner emmy-inline">The 2026 Emmys just happened. <a href="/emmys-2026">What's OK to watch with kids</a> from the nominees and winners.</p>
      </div>
    </div>
  </header>
  <main class="wrap wo-page">
    {_service_nav()}
    <ul class="wo-hub-grid">
      {"".join(cards)}
    </ul>
  </main>"""


def write_whats_on_pages() -> list[tuple[str, str]]:
    """Render hub + six service articles. Returns sitemap (url, priority) tuples."""
    from build_web import (
        BRAND,
        SITE,
        WEB,
        _static_page,
        clip_meta,
        faq_jsonld,
    )

    _require_posters()

    out_dir: Path = WEB / "whats-on"
    if out_dir.exists():
        import shutil

        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    urls: list[tuple[str, str]] = []
    hub_url = f"{SITE}/whats-on/"
    hub_title = "What's on — Family Movies This Week"
    hub_desc = clip_meta(
        "Newly added family movies on Netflix, Disney+, Prime Video, Max, Apple TV+ "
        f"and Paramount+. Updated {UPDATED_DISPLAY}."
    )
    hub_jsonld = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "CollectionPage",
                "url": hub_url,
                "name": hub_title,
                "description": hub_desc,
                "dateModified": UPDATED,
                "isPartOf": {"@id": f"{SITE}/#website"},
            },
            {
                "@type": "ItemList",
                "name": "What's on streaming guides",
                "numberOfItems": len(SERVICES),
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": i + 1,
                        "name": s["h1"],
                        "url": f"{SITE}/whats-on/{s['slug']}",
                    }
                    for i, s in enumerate(SERVICES)
                ],
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Shows", "item": f"{SITE}/"},
                    {"@type": "ListItem", "position": 2, "name": "What's on", "item": hub_url},
                ],
            },
        ],
    }
    (out_dir / "index.html").write_text(
        _static_page(
            url=hub_url,
            title=hub_title,
            desc=hub_desc,
            image=f"{SITE}/covers/kpop-demon-hunters.jpg",
            css_href="../friends.css",
            jsonld=hub_jsonld,
            body=hub_body(),
            prefix="../",
        )
    )
    urls.append((hub_url, "0.9"))

    for svc in SERVICES:
        url = f"{SITE}/whats-on/{svc['slug']}"
        page_title = f"{svc['h1']} ({UPDATED_DISPLAY})"
        desc = clip_meta(svc["desc"])
        items = [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": p["title"],
                "description": f"{p['verdict_label']}. Best for {p['ages']}. {p['mpaa']}.",
            }
            for i, p in enumerate(svc["picks"])
        ]
        jsonld = {
            "@context": "https://schema.org",
            "@graph": [
                {
                    "@type": "Article",
                    "headline": page_title,
                    "name": page_title,
                    "description": desc,
                    "datePublished": UPDATED,
                    "dateModified": UPDATED,
                    "author": {"@type": "Organization", "name": BRAND, "url": SITE},
                    "publisher": {"@id": f"{SITE}/#org"},
                    "mainEntityOfPage": url,
                    "image": f"{SITE}/covers/{svc['cover']}",
                    "articleSection": "What's on",
                    "inLanguage": "en-US",
                },
                {
                    "@type": "ItemList",
                    "name": f"Newly added family titles on {svc['service']}",
                    "numberOfItems": len(items),
                    "itemListElement": items,
                },
                faq_jsonld(svc["faqs"]),
                {
                    "@type": "BreadcrumbList",
                    "itemListElement": [
                        {"@type": "ListItem", "position": 1, "name": "Shows", "item": f"{SITE}/"},
                        {
                            "@type": "ListItem",
                            "position": 2,
                            "name": "What's on",
                            "item": hub_url,
                        },
                        {
                            "@type": "ListItem",
                            "position": 3,
                            "name": svc["service"],
                            "item": url,
                        },
                    ],
                },
            ],
        }
        (out_dir / f"{svc['slug']}.html").write_text(
            _static_page(
                url=url,
                title=page_title,
                desc=desc,
                image=f"{SITE}/covers/{svc['cover']}",
                css_href="../friends.css",
                jsonld=jsonld,
                body=article_body(svc),
                prefix="../",
                og_type="article",
            )
        )
        urls.append((url, "0.85" if svc["slug"].startswith("netflix") else "0.8"))

    print(f"Wrote {len(urls)} What's on pages")
    return urls
